# ====================================================
# Server 3: Hội Nông Dân — hoinongdan.vpdtcampha.vn
# ====================================================
server {
    listen 80;
    server_name hoinongdan.vpdtcampha.vn;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name hoinongdan.vpdtcampha.vn;

    ssl_certificate /etc/nginx/certs/STAR_vpdtcampha_vn_cert_inter_root.crt;
    ssl_certificate_key /etc/nginx/certs/STAR_vpdtcampha_vn_private_key.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    client_max_body_size 50M;

    location / {
        proxy_pass http://hnd_frontend:80;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        proxy_read_timeout 300;
        proxy_connect_timeout 300;
        proxy_send_timeout 300;
    }
}
