name: Deploy to VNPT Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        env:
          VNPT_HOST: ${{ secrets.VNPT_HOST }}
          VNPT_USER: ${{ secrets.VNPT_USER }}
          VNPT_PASS: ${{ secrets.VNPT_PASS }}
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass
          
          sshpass -p "$VNPT_PASS" ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=30 $VNPT_USER@$VNPT_HOST << 'EOF'
            set -e
            cd /root/HoiNongDanPhuong
            git pull origin main
            docker rm -f 9813f87c32c17bf5bb372a801c6156080ca53bd5244775d942697ef1d2b3f5f5 || true
            docker rm -f 3bd51cd8dce8_hnd_backend || true
            docker compose up -d --build
          EOF
